# Generated by Django 4.0.5 on 2022-07-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='finch',
            new_name='finch',
        ),
    ]
